<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<Title>Suttisak's Blazor Identity Templates</Title>
		<Copyright>Suttisak Denduangchai</Copyright>
		<Description>A collection of useful templates for AspNetCore Identity</Description>
		<RepositoryUrl>https://github.com/Lukespacewalker/Suttisak.Blazor</RepositoryUrl>
		<AssemblyVersion>0.9.1</AssemblyVersion>
		<FileVersion>$(AssemblyVersion)</FileVersion>
		<Version>$(AssemblyVersion)</Version>
		<StaticWebAssetsEnabled>True</StaticWebAssetsEnabled>

		<DebugType>Embedded</DebugType>
		<IncludeSymbols>true</IncludeSymbols>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Suttisak.Blazor.Identity.Core\Suttisak.Blazor.Identity.Core.csproj" />
		<ProjectReference Include="..\Suttisak.Blazor.Identity.Generator\Suttisak.Blazor.Identity.Generator.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
		<None Include="..\Suttisak.Blazor.Identity.Generator\bin\$(Configuration)\netstandard2.0\Suttisak.Blazor.Identity.Generator.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Components\Identity\ExternalLoginPicker.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>ExternalLoginPicker.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Components\Identity\ShowRecoveryCodes.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>ShowRecoveryCodes.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Components\Identity\StatusMessage.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>StatusMessage.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\AccessDenied.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>AccessDenied.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\ConfirmEmail.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>ConfirmEmail.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\ConfirmEmailChange.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>ConfirmEmailChange.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\ExternalLogin.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>ExternalLogin.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\ForgotPassword.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>ForgotPassword.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\ForgotPasswordConfirmation.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>ForgotPasswordConfirmation.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\InvalidPasswordReset.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>InvalidPasswordReset.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\InvalidUser.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>InvalidUser.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\Lockout.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Lockout.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\Login.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Login.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\LoginWith2fa.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>LoginWith2fa.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\LoginWithRecoveryCode.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>LoginWithRecoveryCode.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\Manage\ChangePassword.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>ChangePassword.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\Manage\DeletePersonalData.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>DeletePersonalData.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\Manage\Disable2fa.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Disable2fa.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\Manage\Email.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Email.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\Manage\EnableAuthenticator.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>EnableAuthenticator.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\Manage\ExternalLogins.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>ExternalLogins.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\Manage\GenerateRecoveryCodes.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>GenerateRecoveryCodes.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\Manage\Manage.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Manage.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\Manage\Passkeys.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Passkeys.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\Manage\PersonalData.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>PersonalData.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\Manage\Profile.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Profile.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\Manage\RenamePasskey.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>RenamePasskey.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\Manage\ResetAuthenticator.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>ResetAuthenticator.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\Manage\SetPassword.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>SetPassword.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\Manage\TwoFactorAuthentication.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>TwoFactorAuthentication.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\RegisterConfirmation.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>RegisterConfirmation.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\ResendEmailConfirmation.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>ResendEmailConfirmation.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\ResetPassword.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>ResetPassword.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Pages\Identity\ResetPasswordConfirmation.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>ResetPasswordConfirmation.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Region\Identity\ConfirmEmail.razor.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>ConfirmEmail.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Region\Identity\ConfirmEmailChange.razor.Designer.cs">
			<DependentUpon>ConfirmEmailChange.razor.resx</DependentUpon>
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
		</Compile>
		<Compile Update="Region\Identity\UsernamePasswordLogin.razor.Designer.cs">
			<DependentUpon>UsernamePasswordLogin.razor.resx</DependentUpon>
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Components\Identity\ExternalLoginPicker.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>ExternalLoginPicker.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Components\Identity\ShowRecoveryCodes.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>ShowRecoveryCodes.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Components\Identity\StatusMessage.razor.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>StatusMessage.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\AccessDenied.razor.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>AccessDenied.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\ConfirmEmail.razor.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>ConfirmEmail.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\ConfirmEmailChange.razor.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>ConfirmEmailChange.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\ExternalLogin.razor.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>ExternalLogin.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\ForgotPassword.razor.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>ForgotPassword.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\ForgotPasswordConfirmation.razor.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>ForgotPasswordConfirmation.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\InvalidPasswordReset.razor.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>InvalidPasswordReset.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\InvalidUser.razor.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>InvalidUser.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\Lockout.razor.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Lockout.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\Login.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>Login.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\LoginWith2fa.razor.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>LoginWith2fa.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\LoginWithRecoveryCode.razor.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>LoginWithRecoveryCode.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\Manage\ChangePassword.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>ChangePassword.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\Manage\DeletePersonalData.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>DeletePersonalData.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\Manage\Disable2fa.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>Disable2fa.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\Manage\Email.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>Email.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\Manage\EnableAuthenticator.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>EnableAuthenticator.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\Manage\ExternalLogins.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>ExternalLogins.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\Manage\GenerateRecoveryCodes.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>GenerateRecoveryCodes.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\Manage\Manage.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>Manage.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\Manage\Passkeys.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>Passkeys.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\Manage\PersonalData.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>PersonalData.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\Manage\Profile.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>Profile.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\Manage\RenamePasskey.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>RenamePasskey.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\Manage\ResetAuthenticator.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>ResetAuthenticator.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\Manage\SetPassword.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>SetPassword.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\Manage\TwoFactorAuthentication.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>TwoFactorAuthentication.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\RegisterConfirmation.razor.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>RegisterConfirmation.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\ResendEmailConfirmation.razor.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>ResendEmailConfirmation.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\ResetPassword.razor.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>ResetPassword.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Pages\Identity\ResetPasswordConfirmation.razor.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>ResetPasswordConfirmation.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Region\Identity\ConfirmEmail.razor.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>ConfirmEmail.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Region\Identity\ConfirmEmailChange.razor.resx">
			<LastGenOutput>ConfirmEmailChange.razor.Designer.cs</LastGenOutput>
			<Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Region\Identity\UsernamePasswordLogin.razor.resx">
			<LastGenOutput>UsernamePasswordLogin.razor.Designer.cs</LastGenOutput>
			<Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\images\icons\" />
	  <Content Remove="ImageSources\**\*" />
	  <None Update="ImageSources\**\*" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" Pack="false" />
	</ItemGroup>

</Project>
