<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Title>Suttisak's Blazor User Interface Components</Title>
		<Copyright>Suttisak Denduangchai</Copyright>
		<Description>A collection of useful components for Blazor</Description>
		<RepositoryUrl>https://github.com/Lukespacewalker/Suttisak.Blazor</RepositoryUrl>
		<AssemblyVersion>0.1.34</AssemblyVersion>
		<FileVersion>$(AssemblyVersion)</FileVersion>
		<Version>$(AssemblyVersion)</Version>
		<StaticWebAssetsEnabled>True</StaticWebAssetsEnabled>
	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.13.2" />
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.13.2" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Layout\Client\" />
		<Folder Include="Layout\Server\" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Components\Menu\IdentityNavMenuItems.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>IdentityNavMenuItems.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Components\ProfileMenu.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>ProfileMenu.razor.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Components\Menu\IdentityNavMenuItems.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>IdentityNavMenuItems.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Components\ProfileMenu.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>ProfileMenu.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>


</Project>
