<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Title>Suttisak's Blazor User Interface Components</Title>
		<Copyright>Suttisak Denduangchai</Copyright>
		<Description>A collection of useful components for Blazor</Description>
		<RepositoryUrl>https://github.com/Lukespacewalker/Suttisak.Blazor</RepositoryUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<AssemblyVersion>0.26.4</AssemblyVersion>
		<FileVersion>$(AssemblyVersion)</FileVersion>
		<Version>$(AssemblyVersion)</Version>
		<StaticWebAssetsEnabled>True</StaticWebAssetsEnabled>

		<DebugType>Embedded</DebugType>
		<IncludeSymbols>true</IncludeSymbols>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Suttisak.Blazor.Icons\Suttisak.Blazor.Icons.csproj" />
		<SupportedPlatform Include="browser" />
		<None Update="README.md" Pack="true" PackagePath="\" />
		<ProjectReference Include="..\Suttisak.Blazor.UserInterface.Generator\Suttisak.Blazor.UserInterface.Generator.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
		<None Include="..\Suttisak.Blazor.UserInterface.Generator\bin\$(Configuration)\netstandard2.0\Suttisak.Blazor.UserInterface.Generator.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="10.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="10.0.11" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Components\ProfileMenu.razor.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>ProfileMenu.razor.resx</DependentUpon>
		</Compile>
		<Compile Update="Localizations\CommonStrings.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>CommonStrings.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Components\ProfileMenu.razor.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>ProfileMenu.razor.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Localizations\CommonStrings.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>CommonStrings.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>


</Project>
