using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Suttisak.Blazor.UserInterface.Generator;

[Generator]
public sealed class StatusRouteAdapterGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName =
        "Suttisak.Blazor.UserInterface.Routing.GenerateStatusRouteAdaptersAttribute";

    private static readonly ImmutableArray<RoutePage> Pages =
    [
        new("Forbidden", "/forbidden", 403),
        new("NotFound", "/not-found", 404),
        new("Error", "/Error", 500)
    ];

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var requests = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            static (node, _) => node is CompilationUnitSyntax,
            static (attributeContext, _) => CreateRequest(attributeContext));

        context.RegisterSourceOutput(requests, static (productionContext, request) =>
        {
            if (request is not null)
                productionContext.AddSource("StatusRouteAdapters.g.cs", GenerateSource(request));
        });
    }

    private static GenerationRequest CreateRequest(GeneratorAttributeSyntaxContext context)
    {
        var attribute = context.Attributes[0];
        var generatedNamespace = attribute.NamedArguments
            .FirstOrDefault(pair => pair.Key == "Namespace").Value.Value as string;
        if (string.IsNullOrWhiteSpace(generatedNamespace))
            generatedNamespace = context.SemanticModel.Compilation.AssemblyName ?? "StatusRoutes";

        var layoutType = attribute.NamedArguments
            .FirstOrDefault(pair => pair.Key == "LayoutType").Value.Value as ITypeSymbol;
        var excludedPagesArgument = attribute.NamedArguments
            .FirstOrDefault(pair => pair.Key == "ExcludedPages").Value;
        var excludedPageValues = excludedPagesArgument.Kind == TypedConstantKind.Array
            ? excludedPagesArgument.Values
            : ImmutableArray<TypedConstant>.Empty;
        var excludedPages = excludedPageValues
            .Select(value => value.Value as string)
            .Where(static value => !string.IsNullOrWhiteSpace(value))
            .Select(static value => value!)
            .ToImmutableHashSet(StringComparer.Ordinal);

        return new GenerationRequest(
            generatedNamespace!,
            layoutType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            excludedPages);
    }

    private static string GenerateSource(GenerationRequest request)
    {
        var source = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        source.Append("namespace ").Append(request.Namespace).Append(";\n\n");
        source.Append("/// <summary>Routable adapters for the shared HTTP status UI.</summary>\n");
        source.Append("public static class StatusRouteAdapters { }\n\n");

        foreach (var page in Pages)
        {
            if (request.ExcludedPages.Contains(page.Name))
                continue;

            AppendLayout(source, request.LayoutType);
            source.Append("[global::Microsoft.AspNetCore.Components.RouteAttribute(\"")
                .Append(page.Route)
                .Append("\")]\n")
                .Append("public sealed class ")
                .Append(page.Name)
                .Append("StatusRoute : global::Suttisak.Blazor.UserInterface.Routing.StatusRouteAdapter\n")
                .Append("{\n    protected override int ResponseStatusCode => ")
                .Append(page.StatusCode)
                .Append(";\n}\n\n");
        }

        if (!request.ExcludedPages.Contains("StatusCode"))
        {
            AppendLayout(source, request.LayoutType);
            source.Append("[global::Microsoft.AspNetCore.Components.RouteAttribute(\"/status/{StatusCode:int}\")]\n")
                .Append("public sealed class StatusCodeStatusRoute : global::Suttisak.Blazor.UserInterface.Routing.ParameterizedStatusRouteAdapter\n")
                .Append("{\n}\n");
        }

        return source.ToString();
    }

    private static void AppendLayout(StringBuilder source, string? layoutType)
    {
        if (layoutType is not null)
        {
            source.Append("[global::Microsoft.AspNetCore.Components.LayoutAttribute(typeof(")
                .Append(layoutType)
                .Append("))]\n");
        }
    }

    private sealed class GenerationRequest(
        string @namespace,
        string? layoutType,
        ImmutableHashSet<string> excludedPages)
    {
        public string Namespace { get; } = @namespace;
        public string? LayoutType { get; } = layoutType;
        public ImmutableHashSet<string> ExcludedPages { get; } = excludedPages;
    }

    private sealed class RoutePage(string name, string route, int statusCode)
    {
        public string Name { get; } = name;
        public string Route { get; } = route;
        public int StatusCode { get; } = statusCode;
    }
}
