<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Title>Suttisak's Blazor Identity Core Components</Title>
		<Copyright>Suttisak Denduangchai</Copyright>
		<Description>A core component of Suttisak's Blazor Identity</Description>
		<RepositoryUrl>https://github.com/Lukespacewalker/Suttisak.Blazor</RepositoryUrl>
		<AssemblyVersion>0.1.54</AssemblyVersion>
		<FileVersion>$(AssemblyVersion)</FileVersion>
		<Version>$(AssemblyVersion)</Version>
		<StaticWebAssetsEnabled>True</StaticWebAssetsEnabled>

		<DebugType>Embedded</DebugType>
		<IncludeSymbols>true</IncludeSymbols>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="wwwroot\**" />
	  <Content Remove="wwwroot\**" />
	  <EmbeddedResource Remove="wwwroot\**" />
	  <None Remove="wwwroot\**" />
	</ItemGroup>


	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.5" />
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.14.0" />
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.14.0" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Components\Menu\IdentityNavMenuItems.razor.Designer.cs">
			<DependentUpon>IdentityNavMenuItems.razor.resx</DependentUpon>
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Components\Menu\IdentityNavMenuItems.razor.resx">
			<LastGenOutput>IdentityNavMenuItems.razor.Designer.cs</LastGenOutput>
			<Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
	</ItemGroup>

</Project>
