//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suttisak.Blazor.Identity.Pages.Identity.Manage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Passkeys_razor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Passkeys_razor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Suttisak.Blazor.Identity.Pages.Identity.Manage.Passkeys.razor", typeof(Passkeys_razor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ActionHeader {
            get {
                return ResourceManager.GetString("ActionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new passkey.
        /// </summary>
        public static string AddPasskeyButton {
            get {
                return ResourceManager.GetString("AddPasskeyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this passkey from your account.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Could not add the passkey: {0}.
        /// </summary>
        public static string ErrorAddPasskeyFailed {
            get {
                return ResourceManager.GetString("ErrorAddPasskeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The passkey could not be added to your account..
        /// </summary>
        public static string ErrorAddPasskeyToAccount {
            get {
                return ResourceManager.GetString("ErrorAddPasskeyToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The passkey could not be deleted..
        /// </summary>
        public static string ErrorDeletePasskey {
            get {
                return ResourceManager.GetString("ErrorDeletePasskey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The specified passkey ID had an invalid format..
        /// </summary>
        public static string ErrorInvalidPasskeyId {
            get {
                return ResourceManager.GetString("ErrorInvalidPasskeyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: You have reached the maximum number of allowed passkeys..
        /// </summary>
        public static string ErrorMaxPasskeys {
            get {
                return ResourceManager.GetString("ErrorMaxPasskeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The browser did not provide a passkey..
        /// </summary>
        public static string ErrorNoPasskey {
            get {
                return ResourceManager.GetString("ErrorNoPasskey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Unknown action &apos;{0}&apos;..
        /// </summary>
        public static string ErrorUnknownAction {
            get {
                return ResourceManager.GetString("ErrorUnknownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum number of allowed passkeys. Please delete one before adding a new one..
        /// </summary>
        public static string MaxPasskeysReached {
            get {
                return ResourceManager.GetString("MaxPasskeysReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameHeader {
            get {
                return ResourceManager.GetString("NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No passkeys are registered..
        /// </summary>
        public static string NoPasskeys {
            get {
                return ResourceManager.GetString("NoPasskeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passkey deleted successfully..
        /// </summary>
        public static string PasskeyDeleted {
            get {
                return ResourceManager.GetString("PasskeyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string RenameButton {
            get {
                return ResourceManager.GetString("RenameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename this passkey.
        /// </summary>
        public static string RenameTitle {
            get {
                return ResourceManager.GetString("RenameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed passkey.
        /// </summary>
        public static string UnnamedPasskey {
            get {
                return ResourceManager.GetString("UnnamedPasskey", resourceCulture);
            }
        }
    }
}
