name: ci

on:
  push:
    branches: [master]

jobs:
  package-and-publish-lib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Generate NuGet package
        run: |
          dotnet pack Suttisak.Blazor.Identity.Generator/Suttisak.Blazor.Identity.Generator.csproj \
          --configuration Release \
          -o packages
          dotnet pack Suttisak.Blazor.UserInterface/Suttisak.Blazor.UserInterface.csproj \
          --configuration Release \
          -o packages \
          -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          dotnet pack Suttisak.Blazor.Identity.Core/Suttisak.Blazor.Identity.Core.csproj \
          --configuration Release \
          -o packages \
          -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          dotnet pack Suttisak.Blazor.Identity/Suttisak.Blazor.Identity.csproj \
          --configuration Release \
          -o packages \
          -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

      - name: Publish NuGet package
        run: dotnet nuget push packages/*.nupkg --api-key ${{ secrets.PUSH_NUGET }} --source https://nuget.pkg.github.com/LukeSpacewalker/index.json --skip-duplicate
