//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suttisak.Blazor.UserInterface.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Suttisak.Blazor.UserInterface.Localizations.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Actions => ResourceManager.GetString("Actions", resourceCulture);

        public static string Add => ResourceManager.GetString("Add", resourceCulture);

        public static string ApplicationName => ResourceManager.GetString("ApplicationName", resourceCulture);

        public static string Back => ResourceManager.GetString("Back", resourceCulture);

        public static string Cancel => ResourceManager.GetString("Cancel", resourceCulture);

        public static string ClearFilter => ResourceManager.GetString("ClearFilter", resourceCulture);

        public static string Delete => ResourceManager.GetString("Delete", resourceCulture);

        public static string Dialog_DeleteConfirmationBody => ResourceManager.GetString("Dialog_DeleteConfirmationBody", resourceCulture);

        public static string Dialog_DeleteConfirmationBodyCorp => ResourceManager.GetString("Dialog_DeleteConfirmationBodyCorp", resourceCulture);

        public static string Dialog_DeleteConfirmationTitle => ResourceManager.GetString("Dialog_DeleteConfirmationTitle", resourceCulture);

        public static string Edit => ResourceManager.GetString("Edit", resourceCulture);

        public static string Error => ResourceManager.GetString("Error", resourceCulture);

        public static string Filter => ResourceManager.GetString("Filter", resourceCulture);

        public static string HealthExams => ResourceManager.GetString("HealthExams", resourceCulture);

        public static string Interpret => ResourceManager.GetString("Interpret", resourceCulture);

        public static string Next => ResourceManager.GetString("Next", resourceCulture);

        public static string No => ResourceManager.GetString("No", resourceCulture);

        public static string Participant => ResourceManager.GetString("Participant", resourceCulture);

        public static string Participants => ResourceManager.GetString("Participants", resourceCulture);

        public static string Print => ResourceManager.GetString("Print", resourceCulture);

        public static string Register => ResourceManager.GetString("Register", resourceCulture);

        public static string Save => ResourceManager.GetString("Save", resourceCulture);

        public static string Search => ResourceManager.GetString("Search", resourceCulture);

        public static string Summary => ResourceManager.GetString("Summary", resourceCulture);

        public static string Yes => ResourceManager.GetString("Yes", resourceCulture);
    }
}
